### ISSUE TITLE
Multiprocessing causes errors on test of synthetic thermostat data with 2.0 epathermostat branch

### ISSUE THREAD

**Issue by JasonTrager** [EPAENERGYSTAR/epathermostat#52]
I am attempting to use a modification of the multi_thermostat_driver.py.to run a test certification synthetic data. I have run into a series of issues, starting with a problem in the multiprocessing class. 

I was getting an error in from_csv that indicated that elements in result_list was NoneType. After some investigation, I refactored from a for loop to a more iterator friendly form factor as such:

```    
def from_csv(metadata_filename, verbose=False, save_cache=False, shuffle=True,
             cache_path=None, top_n=None, tau_search_path=''):
    """
    Creates Thermostat objects from data stored in CSV files.

    Parameters
    ----------
    metadata_filename : str
        Path to a file containing the thermostat metadata.
    verbose : boolean
        Set to True to output a more detailed log of import activity.
    save_cache: boolean
        Set to True to save the cached data to a json file (based on Thermostat ID).
    shuffle: boolean
        Shuffles the thermostats to give them random ordering if desired (helps with caching).
    cache_path: str
        Directory path to save the cached data.
    log_error: boolean
        Create a log file of thermostats that weren't imported and the reason they weren't imported.
    log_error_filename: boolean
        Name of the file to use for logging the thermostats that weren't imported.

    Returns
    -------
    thermostats : iterator over thermostat.Thermostat objects
        Thermostats imported from the given CSV input files.
    """

    _prime_eeweather_cache()

    metadata = pd.read_csv(
        metadata_filename,
        dtype={
            "thermostat_id": str,
            "heat_type": str,
            "heat_stage": str,
            "cool_type": str,
            "cool_stage": str,
            "zipcode": str,
            "utc_offset": str,
            "interval_data_filename": str
        }
    )
    if top_n is not None:
        metadata = metadata[:top_n]
    metadata.fillna('', inplace=True)
    metadata.columns = map(str.lower, metadata.columns)
    if not METADATA_COLUMNS.issubset(metadata.columns):
        missing_columns = list(METADATA_COLUMNS.difference(metadata.columns))
        message = "Columns missing from metadata data file: {}".format(missing_columns)
        raise ValueError(message)

    # Shuffle the results to help alleviate cache issues
    if shuffle:
        logging.info("Metadata randomized to prevent collisions in cache.")
        metadata = metadata.sample(frac=1).reset_index(drop=True)
    logging.info(f"Metadata Shape: {metadata.shape}")
    p = Pool(AVAILABLE_PROCESSES)
    multiprocess_func_partial = partial(
        _multiprocess_func,
        metadata_filename=metadata_filename,
        verbose=verbose,
        save_cache=save_cache,
        cache_path=cache_path,
        tau_search_path=tau_search_path,
        )
    result_list = p.imap(multiprocess_func_partial, metadata.iterrows())
    p.close()
    p.join()

    results = []
    error_list = []
    print(f"Result List Type: {type(result_list)}")
    try:
        while True:  # Continue until the iterator is exhausted
            result = next(result_list)
            
            # Since we have a result, we can now process it
            if result['thermostat'] is None:
                for error in result['errors']:
                    logging.warning(f"{result['thermostat_id']}: {error}")
                    error_dict = {'thermostat_id': result['thermostat_id'], 'error': error}
                    error_list.append(error_dict)
            else:
                results.append(result['thermostat'])
    except StopIteration:
        # This exception is raised when the iterator is exhausted, which is normal and expected
        pass
    except Exception as e:
        # Catch other exceptions, which could indicate errors in processing individual items
        print(f"Unexpected error processing results: {e}")

    # Convert this to an iterator to maintain compatibility
    return iter(results), error_list
```

I then spoke with @Ethan Goldman, who suggested that I install the environment as specified by the repo. I attempted to do so, and wound up with this error. 

```
(thermostat) jasontrager@Jasons-Macbook-Pro-2024 epathermostat % pip install git+https://github.com/EPAENERGYSTAR/epathermostat.git@feature/epathermostat_2.0

Collecting git+https://github.com/EPAENERGYSTAR/epathermostat.git@feature/epathermostat_2.0
  Cloning https://github.com/EPAENERGYSTAR/epathermostat.git (to revision feature/epathermostat_2.0) to /private/var/folders/f7/t8x8jgb9795c9y__p7v40yl40000gn/T/pip-req-build-_t0z7_st
  Running command git clone --filter=blob:none --quiet https://github.com/EPAENERGYSTAR/epathermostat.git /private/var/folders/f7/t8x8jgb9795c9y__p7v40yl40000gn/T/pip-req-build-_t0z7_st
  Running command git checkout -b feature/epathermostat_2.0 --track origin/feature/epathermostat_2.0
  Switched to a new branch 'feature/epathermostat_2.0'
  branch 'feature/epathermostat_2.0' set up to track 'origin/feature/epathermostat_2.0'.
  Resolved https://github.com/EPAENERGYSTAR/epathermostat.git to commit d8a935c155cc84830ce575def2ad3b16005b4c90
  Preparing metadata (setup.py) ... done
Requirement already satisfied: eeweather==0.3.24 in /Users/jasontrager/opt/anaconda3/envs/thermostat/lib/python3.12/site-packages (from thermostat==2.0.0a7) (0.3.24)
Requirement already satisfied: numpy in /Users/jasontrager/opt/anaconda3/envs/thermostat/lib/python3.12/site-packages (from thermostat==2.0.0a7) (1.26.4)
Requirement already satisfied: pandas in /Users/jasontrager/opt/anaconda3/envs/thermostat/lib/python3.12/site-packages (from thermostat==2.0.0a7) (2.2.1)
Requirement already satisfied: scipy in /Users/jasontrager/opt/anaconda3/envs/thermostat/lib/python3.12/site-packages (from thermostat==2.0.0a7) (1.13.0)
Collecting sqlalchemy<=1.4.46 (from thermostat==2.0.0a7)
  Using cached SQLAlchemy-1.4.46.tar.gz (8.5 MB)
  Preparing metadata (setup.py) ... done
Collecting zipcodes==1.2.0 (from thermostat==2.0.0a7)
  Using cached zipcodes-1.2.0-py2.py3-none-any.whl.metadata (7.4 kB)
Collecting matplotlib==3.4.2 (from thermostat==2.0.0a7)
  Using cached matplotlib-3.4.2.tar.gz (37.3 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/f7/t8x8jgb9795c9y__p7v40yl40000gn/T/pip-install-4xh0ge7u/matplotlib_0ccfc99459c14aee93dca3a073fab26d/setup.py", line 54, in <module>
          __version__ = versioneer.get_version()
                        ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/f7/t8x8jgb9795c9y__p7v40yl40000gn/T/pip-install-4xh0ge7u/matplotlib_0ccfc99459c14aee93dca3a073fab26d/versioneer.py", line 1410, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "/private/var/folders/f7/t8x8jgb9795c9y__p7v40yl40000gn/T/pip-install-4xh0ge7u/matplotlib_0ccfc99459c14aee93dca3a073fab26d/versioneer.py", line 1344, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/f7/t8x8jgb9795c9y__p7v40yl40000gn/T/pip-install-4xh0ge7u/matplotlib_0ccfc99459c14aee93dca3a073fab26d/versioneer.py", line 401, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```

I then updated the setup.py package to use matplotlib 3.8.4 and got the package and branch to install, and then wound up with this same error: 

```
Result List Type: <class 'multiprocessing.pool.IMapIterator'>
2024-04-09 17:08:14,214 - root - WARNING - 1cfa83d1-2670-4779-a340-ac7a8edb9039: 
Unexpected error processing results: 'NoneType' object has no attribute 'index'
2024-04-09 17:08:14,219 - epathermostat - WARNING - Imported 1.5% of thermostats, which is less than 30%
2024-04-09 17:08:14,219 - epathermostat - WARNING - Please check [/Users/jasontrager/Documents/GitHub/energy_star_thermal/data/processed/synthetic/20240408/single_stage/afero-thermostat_2024-04-09_import_errors.csv](https://file+.vscode-resource.vscode-cdn.net/Users/jasontrager/Documents/GitHub/energy_star_thermal/data/processed/synthetic/20240408/single_stage/afero-thermostat_2024-04-09_import_errors.csv) for more details
2024-04-09 17:08:20,744 - root - WARNING - Very-Cold/Cold Climate Zone only has 0 thermostats out of a required 30 thermostats.
2024-04-09 17:08:20,745 - root - WARNING - Mixed-Humid Climate Zone only has 0 thermostats out of a required 30 thermostats.
2024-04-09 17:08:20,746 - root - WARNING - Mixed-Dry/Hot-Dry Climate Zone only has 0 thermostats out of a required 30 thermostats.
2024-04-09 17:08:20,747 - root - WARNING - Hot-Humid Climate Zone only has 5 thermostats out of a required 30 thermostats.
2024-04-09 17:08:20,747 - root - WARNING - Marine Climate Zone only has 0 thermostats out of a required 30 thermostats.
[/Users/jasontrager/Documents/GitHub/epathermostat/thermostat/stats.py:123](https://file+.vscode-resource.vscode-cdn.net/Users/jasontrager/Documents/GitHub/epathermostat/thermostat/stats.py:123): UserWarning: Not enough data to compute summary_statistics (mixed-dry_hot-dry_no_filter_heating)
  warnings.warn(
[/Users/jasontrager/Documents/GitHub/epathermostat/thermostat/stats.py:123](https://file+.vscode-resource.vscode-cdn.net/Users/jasontrager/Documents/GitHub/epathermostat/thermostat/stats.py:123): UserWarning: Not enough data to compute summary_statistics (marine_no_filter_heating)
  warnings.warn(
[/Users/jasontrager/Documents/GitHub/epathermostat/thermostat/stats.py:123](https://file+.vscode-resource.vscode-cdn.net/Users/jasontrager/Documents/GitHub/epathermostat/thermostat/stats.py:123): UserWarning: Not enough data to compute summary_statistics (very-cold_cold_no_filter_heating)
  warnings.warn(
[/Users/jasontrager/Documents/GitHub/epathermostat/thermostat/stats.py:123](https://file+.vscode-resource.vscode-cdn.net/Users/jasontrager/Documents/GitHub/epathermostat/thermostat/stats.py:123): UserWarning: Not enough data to compute summary_statistics (mixed-humid_no_filter_heating)
  warnings.warn(
[/Users/jasontrager/Documents/GitHub/epathermostat/thermostat/stats.py:123](https://file+.vscode-resource.vscode-cdn.net/Users/jasontrager/Documents/GitHub/epathermostat/thermostat/stats.py:123): UserWarning: Not enough data to compute summary_statistics (mixed-humid_no_filter_cooling)
  warnings.warn(
[/Users/jasontrager/Documents/GitHub/epathermostat/thermostat/stats.py:123](https://file+.vscode-resource.vscode-cdn.net/Users/jasontrager/Documents/GitHub/epathermostat/thermostat/stats.py:123): UserWarning: Not enough data to compute summary_statistics (very-cold_cold_no_filter_cooling)
  warnings.warn(
[/Users/jasontrager/Documents/GitHub/epathermostat/thermostat/stats.py:123](https://file+.vscode-resource.vscode-cdn.net/Users/jasontrager/Documents/GitHub/epathermostat/thermostat/stats.py:123): UserWarning: Not enough data to compute summary_statistics (marine_no_filter_cooling)
  warnings.warn(
[/Users/jasontrager/Documents/GitHub/epathermostat/thermostat/stats.py:123](https://file+.vscode-resource.vscode-cdn.net/Users/jasontrager/Documents/GitHub/epathermostat/thermostat/stats.py:123): UserWarning: Not enough data to compute summary_statistics (mixed-dry_hot-dry_no_filter_cooling)
  warnings.warn(
Process SpawnPoolWorker-23:
Process SpawnPoolWorker-25:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/jasontrager/opt/anaconda3/envs/thermostat/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/jasontrager/opt/anaconda3/envs/thermostat/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/jasontrager/opt/anaconda3/envs/thermostat/lib/python3.12/multiprocessing/process.py", line 108, in run
...
  File "/Users/jasontrager/opt/anaconda3/envs/thermostat/lib/python3.12/multiprocessing/queues.py", line 389, in get
    return _ForkingPickler.loads(res)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Can't get attribute '5aa6ea438cce45dcb2324df71ed59301' on <module 'thermostat.stats' from '/Users/jasontrager/Documents/GitHub/epathermostat/thermostat/stats.py'>
```

I am on a Apple M3 Max 2024. 

Here is the pip list of the environment: 

```Package             Version  Editable project location
------------------- -------- -------------------------------------------------------
appnope             0.1.4
asttokens           2.4.1
certifi             2024.2.2
charset-normalizer  3.3.2
click               8.1.7
comm                0.2.2
contourpy           1.2.1
cycler              0.12.1
debugpy             1.6.7
decorator           5.1.1
dill                0.3.8
eemeter             3.1.0
eeweather           0.3.24
energy-star-thermal 0.1.0
energystarthermal   0.1.0    /Users/jasontrager/Documents/GitHub/energy_star_thermal
exceptiongroup      1.2.0
executing           2.0.1
fonttools           4.51.0
greenlet            3.0.3
idna                3.6
importlib_metadata  7.1.0
ipykernel           6.29.3
ipython             8.22.2
jedi                0.19.1
jupyter_client      8.6.1
jupyter_core        5.5.0
kiwisolver          1.4.5
loguru              0.7.2
matplotlib          3.8.4
matplotlib-inline   0.1.6
nest_asyncio        1.6.0
numpy               1.26.4
packaging           24.0
pandarallel         1.6.5
pandas              2.2.1
parso               0.8.4
patsy               0.5.6
pexpect             4.9.0
pickleshare         0.7.5
pillow              10.3.0
pip                 23.3.1
platformdirs        4.2.0
prompt-toolkit      3.0.42
psutil              5.9.0
ptyprocess          0.7.0
pure-eval           0.2.2
Pygments            2.17.2
pyparsing           3.1.2
pyproj              3.6.1
python-dateutil     2.9.0
pytz                2024.1
pyzmq               25.1.2
requests            2.31.0
scipy               1.13.0
setuptools          68.2.2
shapely             2.0.3
six                 1.16.0
SQLAlchemy          1.4.46
stack-data          0.6.2
statsmodels         0.14.1
thermostat          2.0.0a7  /Users/jasontrager/Documents/GitHub/epathermostat
tornado             6.3.3
traitlets           5.14.2
typing_extensions   4.11.0
tzdata              2024.1
urllib3             2.2.1
wcwidth             0.2.13
wheel               0.41.2
zipcodes            1.2.0
zipp                3.17.0
```

**Comment by john-zither** [comment]
Hi,

I believe the None type error is due to `_calculate_cool_runtime` and `_calculate_heat_runtime` causing the code to fail by returning None, but only providing a warning.

@EthanGoldman and @AbhishekJathar131294 in cases where a thermostat is provided with Multi-stage heating, should the entire script crash, or should it just include that thermostat on the list of errors?
